name: Update Database

on:
  workflow_dispatch:
  schedule:
    # At 1 AM UTC from Tuesday to Saturday (8 PM EST / 9 PM EDT Monday-Friday)
    - cron: '0 1 * * 2-6'
    # At 9 PM UTC on Saturday (4 PM EST / 5 PM EDT Saturday)
    - cron: '0 21 * * 6'
    # At 9 PM UTC on Sunday (4 PM EST / 5 PM EDT Sunday)
    - cron: '0 21 * * 0'

jobs:
  update_database:
    runs-on: ubuntu-latest
    env:
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
      NYT_S_TOKEN: ${{ secrets.NYT_S_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - name: Update database
        run: python -u scripts/update_db.py
