name: Update Database

on:
  workflow_dispatch:
  schedule:
    # At 11 PM UTC from Monday to Friday (6 PM EST / 7 PM EDT Monday-Friday)
    - cron: '0 23 * * 1-5'
    # At 7 PM UTC on Saturday (2 PM EST / 3 PM EDT Saturday)
    - cron: '0 19 * * 6'
    # At 7 PM UTC on Sunday (2 PM EST / 3 PM EDT Sunday)
    - cron: '0 19 * * 0'

jobs:
  update_database:
    runs-on: ubuntu-latest
    env:
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
      NYT_S_TOKEN: ${{ secrets.NYT_S_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - name: Update database
        run: python -u scripts/update_db.py
